export const DIVINER_TYPES = {
  AddressHistoryDiviner: 'AddressHistoryDiviner',
  AddressSpaceBatchDiviner: 'AddressSpaceBatchDiviner',
  AddressSpaceDiviner: 'AddressSpaceDiviner',
  BoundWitnessDiviner: 'BoundWitnessDiviner',
  BoundWitnessStatsDiviner: 'BoundWitnessStatsDiviner',
  ElevationDiviner: 'ElevationDiviner',
  ForecastingDiviner: 'ForecastingDiviner',
  ImageThumbnailDiviner: 'ImageThumbnailDiviner',
  NftCollectionScoreDiviner: 'NftCollectionScoreDiviner',
  NftScoreDiviner: 'NftScoreDiviner',
  PayloadDiviner: 'PayloadDiviner',
  PayloadStatsDiviner: 'PayloadStatsDiviner',
  SchemaListDiviner: 'SchemaListDiviner',
  SchemaStatsDiviner: 'SchemaStatsDiviner',
}
